services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
     - '8761:8761'
    expose:
     - '8761'
    restart: always

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    expose:
     - '9999'
    restart: always
  gateway-service:

    build: ./service-gateway
    container_name: gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    restart: always

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    restart: always

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    restart: always
